# Created by Jekyll Writer
title: 我TM吹爆
author: lymastee
description: 'Test description bla~bla~bla~'
show_downloads: false
permalink: '/:year/:month/:day/:title/'
paginate: 6
paginate_path: '/page/:num/'
twitter_username: ''
github_username: lymastee
gems:
  - jekyll-paginate
markdown: kramdown
baseurl: ''
theme: jekyll-theme-modernist
